INSERT INTO listings (image_url, seller_id, title, created_at, featured, price, description, active)
VALUES
('https://www.pennlive.com/resizer/q4MdM3Gub1X3sKlztIqr_M4pz8I=/1280x0/smart/advancelocal-adapter-image-uploads.s3.amazonaws.com/image.pennlive.com/home/penn-media/width2048/img/entertainment_impact/photo/ar2png-ea54ef18a4cdc7e9.png', 6, 'War', 'April 17, 2019', true, 50, 'Re-run of the 2008 vinyl remaster of U2 third studio album originally released in 1983. Includes all ten album tracks remastered in 2008, plus expanded 16 page booklet as per the 2008 release.', true),
('http://thevinylfactory.com/wp-content/uploads/2017/03/nico.jpg', 6, 'The Velvet Underground & Nico', 'March 22, 2019', true, 30, 'There are three versions of the back cover of the original American release: 1st - Has an image of actor Eric Emerson projected upside-down on the wall behind the band.',true),
        ('https://www.pennlive.com/resizer/86mZUQKbnvW1xaS8h7_cymGbJbs=/1280x0/smart/advancelocal-adapter-image-uploads.s3.amazonaws.com/image.pennlive.com/home/penn-media/width2048/img/entertainment_impact/photo/22389044-standard.jpg', 7, 'News of the World', 'February 8, 2019', true, 22, 'Experimental rock, Proto-punk, Avant-garde music, Dream pop',false),
        ('https://www.udiscovermusic.com/wp-content/uploads/2019/04/Massive-Attack-Mezzanine-album-cover-web-optimised-820.jpg', 8, 'Mezzanine', 'October 18, 2019', true, 29, 'Mezzanine is the third studio album by English electronic music group Massive Attack, released on 20 April 1998 by Circa and Virgin Records. *Mezzanine* was a document of unity, not fragmentation. ',false),
        ('https://www.nme.com/wp-content/uploads/2017/11/Run-the-Jewels-2-artwork.jpg', 8, 'My Björk live', 'September 6, 2019', true, 22, 'Backstory: I really dislike the album covers for the first 4 live albums so I decided to create my own and in the process I ended up doing all albums! (Yes even Medúlla and Utopia for which there are no official live album released). I wanted to make them all cohesive but still in line which each eras aesthetics so I hope I managed to do so...', true),
        ('https://media.npr.org/assets/img/2011/10/10/img_0030-48f68a61e4f067937cf164dd11c637cdf7287823-s1500-c85.webp', 9, 'Biophilia', 'January 17, 2020', false, 27,'Biophilia marks her eighth full-length release, and represents her definitive attempt to create an ecosystem around her work. Billed as her most ambitious and interdisciplinary project yet and boasting all the usual fixings of a Björk release (dazzling artwork, a Michel Gondry video, vanguard instrumentation, a bizarre list of collaborators), it also comes supported by a corresponding iPad application for each of its 10 tracks, a new website, a series of live shows and a forthcoming 90-minute film documenting its creation.', true),
        ('https://d33wubrfki0l68.cloudfront.net/5cda35fc1476fe845aa79798581862c550ffbdaa/3cf07/media/homogenic.jpg', 9, 'Homogenic album. Art directed by Alexander McQueen, no less', 'January 17, 2020', true, 30, 'Homogenic is the third studio album by Icelandic recording artist Björk. It was released on 22 September 1997 in the United Kingdom by One Little Indian Records and in the United States by Elektra Entertainment.',true),
        ('https://www.nme.com/wp-content/uploads/2016/10/3.2013_Portishead_dummy_281013-4.jpg', 9, 'Portishead – Dummy', 'February 14, 2020', false, 40, 'Portishead – Dummy: A still from the 10-minute short film ‘To Kill A Dead Man’, a spy movie homage starring Barrow as a rooftop assassin and Gibbons as the distraught wife of the man he’s contracted to kill.',true),
        ('https://cdn.shortpixel.ai/client/q_glossy,ret_img/https://creativesfeed.com/wp-content/uploads/2018/08/Roots-by-Ahmed-Emad-Eldin.jpg', 2, 'Great Buy', 'January 01, 2020', false, 20, 'The last Pink Floyd studio album, The Endless River (2014), was based on unreleased material from the Division Bell recording sessions. Sleeve was designed by Ahmed Emad Eldin (Arabic: أحمد عماد الدين‎), an Egyptian digital artist.',true),
        ('https://img.discogs.com/Mbar84pxnCM8yry6-527NKqoY6g=/fit-in/520x520/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-7816021-1512767053-9568.jpeg.jpg', 2, 'Hard to find first edition by Morcheeba', 'February 14, 2020',false, 100, 'Big Calm is the second studio album by English electronic music group Morcheeba. It was released in March 1998 by Indochina Records and Sire Records. The album reached the top 20 of the UK Albums Chart, while the single <Part of the Process> charted in the top 40 of the UK Singles Chart in August of the same year.',true);
