INSERT INTO chats (from_id, to_id, listing_id, txt_msg, date_time)
VALUES (2, 2, 1, 'can you bring down the price?',Now()),
(1, 2, 1, 'The item is reasonably priced. What are you offerring?', Now()),
(2, 2, 1, '45', Now()),
(1, 2, 1, 'Sold!', Now()),
(2, 2, 1, 'Thank you', Now()),
(3, 3, 3, 'Is this available?', Now()),
(1, 3, 3, 'Yes. What are you offerring?', Now()),
(3, 3, 3, '35', Now()),
(1, 3, 3, 'Sold!', Now()),
(3, 3, 3, 'Thank you', Now()),
(2, 2, 5, 'is this available', Now()),
(1, 2, 5, 'yes. What are you offerring?', Now()),
(3, 3, 5, 'is this available', Now()),
(1, 3, 5, 'yes. someone else is also looking?', Now()),
(2, 2, 5, '25', Now()),
(1, 2, 5, 'Sold!', Now()),
(2, 2, 5, 'Thank you', Now()),
(4, 4, 6, 'Is this available?', Now()),
(1, 4, 6, 'Yes', Now()),
(4, 4, 6, 'Is the price fixed?', Now()),
(1, 4, 6, 'Open to negotiations. How much do you want it for?', Now());
