DROP TABLE IF EXISTS listingItems CASCADE;

CREATE TABLE listingItems (
  id SERIAL PRIMARY KEY NOT NULL,
  listing_id INTEGER REFERENCES listings (id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products(id) ON DELETE CASCADE
);
