DROP TABLE IF EXISTS chats CASCADE;
CREATE TABLE chats (
  id SERIAL PRIMARY KEY NOT NULL,
  from_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  to_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  listing_id INTEGER REFERENCES listings (id) ON DELETE CASCADE,
  read BOOLEAN NOT NULL DEFAULT FALSE,
  txt_msg text NOT NULL,
  date_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
